<h5>코드에는 틀린곳이 없다고 떠도 실행을 눌러보면 오류(예외?)가 뜰 수 있구나...</h5>

```java
package day_14;

public class ExceptionTest {

	public static void main(String[] args) {
		int val1 = 10;
		int val2 = 1;
		
//		System.out.println(val1 / --val2); ←여기도 주석 풀면 오류남
		
		int[] val3 = new int[3];
		System.out.println(val3[3]);
		
		int result = val1 + val2;
		System.out.println(result);
	}

}
```
<h5>차라리 코드에 틀린부분이 있다고 뜨는게 낫지,,,<br>
뭔가 만들었는데 이런식으로 실행이 안되면 
과연 나는 찾아내서 고칠 수 있을까..?</h5>

```java
package day_14;

public class ExceptionTest {

	public static void main(String[] args) {
		int val1 = 10;
		int val2 = 1;
		
		try {
			System.out.println(val1 / --val2);
			
			int[] val3 = new int[3];
			System.out.println(val3[3]);
			
			int result = val1 + val2;
			System.out.println(result);
			
		} catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("배열의 범위를 벗어났습니다.");
		} catch (ArithmeticException e) {
			System.out.println("0으로 나누려는 시도를 하고 있습니다.");
		}
		
	}

}
```

<h5>스스로 이렇게 할 수 있어야한다..!</h5>

```java
	catch (ArrayIndexOutOfBoundsException | ArithmeticException e) {
		System.out.println("배열의 범위를 벗어났거나,");
		System.out.println("0으로 나누려는 시도를 하고 있습니다.");
	}
```
<h5>이렇게 한번에 쓰면 줄을 좀 더 줄일 수 있다..</h5>

```java
	catch (NullPointerException e) {
		System.out.println("null point exception.");
			
		System.out.println("error = " + e.getMessage());
```
<h5>으아악</h5>

```java
public class ExceptionTest {
	private static String text;

	public static void main(String[] args) {
		Scanner scanf = new Scanner(System.in);

		int val1 = 10;
		int val2 = 1;
		int[] val3 = null; //←메서드 안에서 선언된 변수는 지역 변수이기 때문에 꼭 값을 초기화 해줘야 한다.
```
<h5>항상 생각하기</h5>
